version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salarium
    ports:
      - "8080:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/salarium.db
      - JWT_SECRET=${JWT_SECRET:-super-secret-change-me}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_WORKERS=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
